name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.0
  - python=3.12.4
  - readline=8.2
  - setuptools=70.1.1
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - asgiref==3.8.1
      - django==5.0.6
      - django-cors-headers==4.4.0
      - djangorestframework==3.15.2
      - psycopg2-binary==2.9.9
      - sqlparse==0.5.0
